export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const REGISTER_USER_BEGIN_ADMIN = "REGISTER_USER_BEGIN_ADMIN";
export const REGISTER_USER_SUCCESS_ADMIN = "REGISTER_USER_SUCCESS_ADMIN";
export const REGISTER_USER_ERROR_ADMIN = "REGISTER_USER_ERROR_ADMIN";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT-USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const REPORT_PROBLEM_BEGIN = "REPORT_PROBLEM_BEGIN";
export const REPORT_PROBLEM_SUCCESS = "REPORT_PROBLEM_SUCCESS";
export const REPORT_PROBLEM_ERROR = "REPORT_PROBLEM_ERROR";

export const GET_COURSES_INSTRUCTOR_BEGIN = "GET_COURSES_INSTRUCTOR_BEGIN";
export const GET_COURSES_INSTRUCTOR_SUCCESS = "GET_COURSES_INSTRUCTOR_SUCCESS";

export const INC_VIEWERS_BEGIN = "INC_VIEWERS_BEGIN";
export const INC_VIEWERS_SUCCESS = "INC_VIEWERS_SUCCESS";

export const CHANGE_ALERT_TEXT = "CHANGE_ALERT_TEXT";
